### ISSUE TITLE
Send form-data

### ISSUE THREAD

**Issue by YerkoPalma** [lukeed/httpie#24]
Hi 👋 
I want to send a form-data request with httpie and I haven't found how.
[Axios](https://github.com/axios/axios#form-data) and [Got](https://github.com/sindresorhus/got#body), use the [form-data](https://github.com/form-data/form-data) library. I haven't tried it yet in httpie, but is this the way to go here? 

By the way, my attempt was like this

```js
const res = await post('https://api.instagram.com/oauth/access_token', {
        body: {
          client_id: process.env.APP_ID,
          client_secret: process.env.APP_SECRET,
          grant_type: 'authorization_code',
          redirect_uri: process.env.REDIRECT_URI,
          code: req.query.code
        },
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      })
```

**Comment by lukeed** [comment]
Hey hey,

I would use rely on natives if your support targets can allow it – `URLSearchParams`  is pretty old by now so you should be okay there.

```js
let usp = new URLSearchParams({
  client_id: process.env.APP_ID,
  client_secret: process.env.APP_SECRET,
  grant_type: 'authorization_code',
  redirect_uri: process.env.REDIRECT_URI,
  code: req.query.code
});

// can append() or sort() or ...

await post('https://...', {
  body: usp.toString(),
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded' // or 'multipart/form-data'
  }
});
```

If you're working with forms, you can do something like this:

```js
let elem = document.querySelector('#myform');

let data = new FormData(elem);
let body = new URLSearchParams(data).toString();

await post('https://...', { body, ... }); // same headers as above
```

If you need some older browser support, you can use something like [`qss`](https://github.com/lukeed/qss) to encode your data object into a query string format – just omit the `prefix` argument since your example is sending as POST body and not GET parameters.

Hope that helps~!

**Comment by YerkoPalma** [comment]
I'll check with `URLSearchParams` thanks for the answer
