### ISSUE TITLE
Here is an possibly an error with FormData (v2)

### ISSUE THREAD

**Issue by dima-takoy-zz** [lukeed/httpie#27]
When i try use this lib with FormData i got an error.

https://github.com/lukeed/httpie/blob/v2.0.0-next.7/src/fetch.js#L15

**Comment by lukeed** [comment]
Hey,

Because FormData is not an isomorphic construct, httpie doesn't auto-cast for you. It's very easy to do within your browser code; you just need to include it as part of your wrapper.

You can see my answer [here](https://github.com/lukeed/httpie/issues/24#issuecomment-626803806) for actually preparing FormData for transport.

In my own projects, here's what my client-side API utility will look like:

```js
import * as httpie from 'httpie';

const API = new URL('https://...');

export function send(method, pathname, data, opts = {}) {
  opts.headers = opts.headers || {};
  
  // check local/session storage for Authorization info
  let token = get_local_token();
  if (token) opts.headers.Authorization = `Bearer ${token}`;

  if (data instanceof FormData) {
    opts.body = new URLSearchParams(data).toString();
    if (opts.body.length) opts.headers['Content-Type'] = 'application/x-www-form-urlencoded';
  } else if (data) {
    opts.body = body; // httpie will take care of it
  }

  return httpie.send(method, new URL(path, API), opts);
}
```

Hope that helps!
