### ISSUE TITLE
withCredentials

### ISSUE THREAD

**Issue by anonimusprogramus** [lukeed/httpie#32]
Hi Luke,
how's to set withCredentials with httpie@next?

Thanks

**Comment by lukeed** [comment]
Hey,

For both browser variants, just use `opts.withCredentials` it maps over directly (eg, https://github.com/lukeed/httpie/blob/next/src/xhr.js#L53). There's no equivalent in Node because it doesn't apply, so you can use the same set of options and Node variant will ignore it:

```js
httpie.send('GET', '...', {
  with credentials: true,
  headers: { ... }
})
```

Hope that helps

**Comment by lukeed** [comment]
Hey, just following up. Did this work okay for you?

**Comment by anonimusprogramus** [comment]
I'm sorry, atm on mobile. Gonna try it asap. Thanks

**Comment by anonimusprogramus** [comment]
Confirmed, it works! :tada:

There's even suggestion on vscode lol. My bad I didn't look into source 1st before asking. As always, thank you so much :raised_hands:

**Comment by paulocoghi** [comment]
Luke is one of the best open source software creators I know.

I am even a little concerned about his normal work and personal life, because he responds always so fast, many times with code examples.

He deserves 1000 sponsors. :smile: And we, your library users, may seriously consider to be one of them.

**Comment by lukeed** [comment]
Haha thank you @paulocoghi, appreciate the kind words
